sudo: false
language: rust
cache: cargo

matrix:
  include:
    - rust: stable
       env: RUST_VERSION=stable COMMAND=test

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test

    - rust: stable
      env: COMMAND=lint

script:
  - make $COMMAND
  - cargo check --benches --all-features
  - |
    [ "$RUST_VERSION" = "nightly" ] && exit 0 # Don't cargo-fmt on nightly
    make style-check

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
