[package]
name = "redis"
version = "0.11.1-alpha.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>", "Jan-Erik Rediger <janerik@fnordig.de>"]
keywords = ["redis", "database"]
description = "Redis driver for Rust."
homepage = "https://github.com/mitsuhiko/redis-rs"
repository = "https://github.com/mitsuhiko/redis-rs"
documentation = "https://docs.rs/redis"
license = "BSD-3-Clause"
readme = "README.md"
edition = "2018"

[dependencies]
dtoa = "0.4"
itoa = "0.4.3"
sha1 = ">= 0.2, < 0.7"
url = "1.2"
combine = "3.8.1"
bytes = "0.4"
futures = "0.1"
tokio-executor = { version = "0.1", optional = true }
tokio-tcp = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-sync = "0.1"

[features]
default = [ "executor", "geospatial" ]

geospatial = []
executor = [ "tokio-executor" ]

[target.'cfg(unix)'.dependencies]
tokio-uds = { version = "0.2" }

[dev-dependencies]
rand = "0.4"
net2 = "0.2"
assert_approx_eq = "1.0"
fnv = "1.0.5"
criterion = "0.2"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
quickcheck = "0.6"
tokio = "0.1"

[[bench]]
name = "bench_basic"
harness = false
