[package]
name = "redis"
version = "0.8.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["redis", "database"]
description = "Redis driver for Rust."
homepage = "https://github.com/mitsuhiko/redis-rs"
documentation = "http://mitsuhiko.github.io/redis-rs/"
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

#[dependencies.sha1]
#git = "https://github.com/mitsuhiko/rust-sha1.git"
#
#[dependencies.url]
#git = "https://github.com/servo/rust-url"

[features]
with-rustc-json = ["rustc-serialize"]
with-unix-sockets = ["unix_socket"]
# with-async-unix-sockets = ["tokio-uds"]
with-system-unix-sockets = []

[dependencies]
sha1 = ">= 0.2, < 0.7"
url = "1.2"
rustc-serialize = { version = "0.3.16", optional = true }
unix_socket = { version = "0.5.0", optional = true }
net2 = "0.2"
combine = "3.0.0"
futures = "0.1"
tokio-reactor = "0.1"
tokio-tcp = "0.1"
tokio-io = "0.1"
# tokio-uds = { git = "https://github.com/Marwes/tokio-uds", branch = "only_tokio_upgrade", optional = true }

[dev-dependencies]
rand = "0.4"
net2 = "0.2"
bencher = "0.1"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
quickcheck = "0.6"
tokio = "0.1"

[[bench]]
name = "bench_basic"
harness = false

